/**
 * Standard Error Codes for API Responses
 */

const ERROR_CODES = {
  // Organization errors
  ORG_ALREADY_EXISTS: "ORG_ALREADY_EXISTS",
  ORG_NOT_FOUND: "ORG_NOT_FOUND",
  ORG_NAME_REQUIRED: "ORG_NAME_REQUIRED",

  // Authentication errors
  UNAUTHORIZED: "UNAUTHORIZED",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
  TOKEN_INVALID: "TOKEN_INVALID",
  TOKEN_MISSING: "TOKEN_MISSING",

  // Validation errors
  VALIDATION_ERROR: "VALIDATION_ERROR",
  INVALID_INPUT: "INVALID_INPUT",

  // Server errors
  SERVER_ERROR: "SERVER_ERROR",
  DATABASE_ERROR: "DATABASE_ERROR",

  // Collection errors
  COLLECTION_CREATE_FAILED: "COLLECTION_CREATE_FAILED",
  COLLECTION_DELETE_FAILED: "COLLECTION_DELETE_FAILED",
  COLLECTION_MIGRATE_FAILED: "COLLECTION_MIGRATE_FAILED",
};

module.exports = ERROR_CODES;
